---
name: Exception-Died
version: 0.04
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: Convert simple die into real exception object
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Base: 0.2
  perl: 5.006
build_requires:
  Test::Unit::Lite: 0.1
provides:
  Exception::Died:
    file: lib/Exception/Died.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
